Repository willem445/PasswordVault, pull requests merged in 2019-11, with the labels that each got.

#74 Is63 create web api project
  PasswordVault.Data/App.config
  PasswordVault.Data/CSV/CsvManager/CsvPasswordManager.cs
  PasswordVault.Data/CSV/CsvManager/CsvUserManager.cs
  PasswordVault.Data/CSV/CsvManager/ICsvPasswordManager.cs
  PasswordVault.Data/CSV/CsvManager/ICsvUserManager.cs
  PasswordVault.Data/CSV/Reader/CSVReader.cs
  PasswordVault.Data/CSV/Reader/ICsvReader.cs
  PasswordVault.Data/CSV/Writer/CsvWriter.cs
  PasswordVault.Data/CSV/Writer/ICsvWriter.cs
  PasswordVault.Data/CsvDatabase.cs
  PasswordVault.Data/IDatabase.cs
  PasswordVault.Data/InMemoryDatabase.cs
  PasswordVault.Data/MySqlDatabase.cs
  PasswordVault.Data/PasswordVault.Data.csproj
  PasswordVault.Data/Properties/AssemblyInfo.cs
  PasswordVault.Data/SQLiteDatabase.cs
  PasswordVault.Data/packages.config
  PasswordVault.Desktop.Winforms/NinjectBindings.cs
  PasswordVault.Desktop.Winforms/PasswordVault.Desktop.Winforms.csproj
  PasswordVault.Desktop.Winforms/Properties/AssemblyInfo.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
  PasswordVault.Desktop.Winforms/packages.config
  PasswordVault.Models/DatabasePassword.cs
  PasswordVault.Models/Password.cs
  PasswordVault.Models/PasswordVault.Models.csproj
  PasswordVault.Models/Properties/AssemblyInfo.cs
  PasswordVault.Models/User.cs
  PasswordVault.Models/packages.config
  PasswordVault.Services/.editorconfig
  PasswordVault.Services/EncryptionService/AesEncryption.cs
  PasswordVault.Services/EncryptionService/IEncryptionService.cs
  PasswordVault.Services/EncryptionService/RijndaelManagedEncryption.cs
  PasswordVault.Services/IUserAuthentication.cs
  PasswordVault.Services/MasterPasswordService/IMasterPassword.cs
  PasswordVault.Services/MasterPasswordService/MasterPassword.cs
  PasswordVault.Services/MasterPasswordService/MasterPasswordTypes.cs
  PasswordVault.Services/PasswordService/IPasswordService.cs
  PasswordVault.Services/PasswordService/PasswordService.cs
  PasswordVault.Services/PasswordService/PasswordServiceTypes.cs
  PasswordVault.Services/PasswordVault.Services.csproj
  PasswordVault.Services/Properties/AssemblyInfo.cs
  PasswordVault.Services/UriUtilities.cs
  PasswordVault.Services/packages.config
  PasswordVault.ServicesTests/DatabaseFactory.cs
  PasswordVault.ServicesTests/PasswordVault.ServicesTests.csproj
  PasswordVault.Web/PasswordVault.Web.csproj
  PasswordVault.Web/Properties/AssemblyInfo.cs
  PasswordVault.WebApi/Controllers/PasswordController.cs
  PasswordVault.WebApi/Controllers/UserController.cs
  PasswordVault.WebApi/Helpers/AppSettings.cs
  PasswordVault.WebApi/Models/AuthenticateModel.cs
  PasswordVault.WebApi/PasswordVault.WebApi.csproj
  PasswordVault.WebApi/Program.cs
  PasswordVault.WebApi/Properties/launchSettings.json
  PasswordVault.WebApi/Startup.cs
  PasswordVault.WebApi/appsettings.Development.json
  PasswordVault.WebApi/appsettings.json
  PasswordVault.Winforms.Installer/PasswordVault.Winforms.Installer.vdproj
  PasswordVault.sln
Labels: backend, webapi

#73 change filter to be case insensitive
  PasswordVault.Desktop.Winforms/Presenters/MainPresenter.cs
Labels: desktopapp, feature, frontend

#76 Is66 seperate password service logic
  PasswordVault.Data/IDatabase.cs
  PasswordVault.Data/InMemoryDatabase.cs
  PasswordVault.Data/MySqlDatabase.cs
  PasswordVault.Data/SQLiteDatabase.cs
  PasswordVault.Desktop.Winforms/Logic/DesktopServiceWrapper/DesktopServiceWrapper.cs
  PasswordVault.Desktop.Winforms/Logic/DesktopServiceWrapper/IDesktopServiceWrapper.cs
  PasswordVault.Desktop.Winforms/NinjectBindings.cs
  PasswordVault.Desktop.Winforms/PasswordVault.Desktop.Winforms.csproj
  PasswordVault.Desktop.Winforms/Presenters/ChangePasswordPresenter.cs
  PasswordVault.Desktop.Winforms/Presenters/EditUserPresenter.cs
  PasswordVault.Desktop.Winforms/Presenters/LoginPresenter.cs
  PasswordVault.Desktop.Winforms/Presenters/MainPresenter.cs
  PasswordVault.Desktop.Winforms/Program.cs
  PasswordVault.Desktop.Winforms/Views/ChangePasswordView.cs
  PasswordVault.Desktop.Winforms/Views/IChangePasswordView.cs
  PasswordVault.Desktop.Winforms/Views/ILoginView.cs
  PasswordVault.Desktop.Winforms/Views/IMainView.cs
  PasswordVault.Desktop.Winforms/Views/LoginView.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
  PasswordVault.Models/Password.cs
  PasswordVault.Models/User.cs
  PasswordVault.Services/AppSettings.cs
  PasswordVault.Services/AuthenticationService/AuthenticationService.cs
  PasswordVault.Services/AuthenticationService/AuthenticationServiceTypes.cs
  PasswordVault.Services/AuthenticationService/IAuthenticationService.cs
  PasswordVault.Services/EncryptionService/Conversions/RijndaelToAesConversion.cs
  PasswordVault.Services/IUserAuthentication.cs
  PasswordVault.Services/KeyGenerator.cs
  PasswordVault.Services/PasswordService/IPasswordService.cs
  PasswordVault.Services/PasswordService/PasswordService.cs
  PasswordVault.Services/PasswordService/PasswordServiceTypes.cs
  PasswordVault.Services/PasswordVault.Services.csproj
  PasswordVault.Services/TokenService/ITokenService.cs
  PasswordVault.Services/TokenService/TokenService.cs
  PasswordVault.Services/UserService/IUserService.cs
  PasswordVault.Services/UserService/UserService.cs
  PasswordVault.Services/UserService/UserServiceTypes.cs
  PasswordVault.ServicesTests/DesktopPasswordServiceBuilder.cs
  PasswordVault.ServicesTests/PasswordService/Password/AddPasswordTests.cs
  PasswordVault.ServicesTests/PasswordService/Password/DeletePasswordTests.cs
  PasswordVault.ServicesTests/PasswordService/Password/ModifyPasswordTests.cs
  PasswordVault.ServicesTests/PasswordService/User/ChangeUserPasswordTests.cs
  PasswordVault.ServicesTests/PasswordService/User/CreateUserTests.cs
  PasswordVault.ServicesTests/PasswordService/User/DeleteUserTests.cs
  PasswordVault.ServicesTests/PasswordService/User/LoginTests.cs
  PasswordVault.ServicesTests/PasswordService/User/ModifyUserTests.cs
  PasswordVault.ServicesTests/PasswordServiceTests.cs
  PasswordVault.ServicesTests/PasswordVault.ServicesTests.csproj
  PasswordVault.ServicesTests/packages.config
  PasswordVault.WebApi/Controllers/PasswordController.cs
  PasswordVault.WebApi/Services/Authentication/WebAuthenticationService.cs
  PasswordVault.WebApi/appsettings.json
Labels: feature

#77 IS71 Add Generate Password Options
  PasswordVault.Desktop.Winforms/Presenters/MainPresenter.cs
  PasswordVault.Desktop.Winforms/Views/IMainView.cs
  PasswordVault.Desktop.Winforms/Views/MainView.Designer.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
Labels: feature, frontend

#78 IS37 Delete Filtered Password Broken
  PasswordVault.Desktop.Winforms/Presenters/MainPresenter.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
Labels: bug, frontend

#79 IS61 Improve Data Grid View Display
  PasswordVault.Data/SQLiteDatabase.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
  PasswordVault.Services/PasswordVault.Services.csproj
  PasswordVault.ServicesTests/PasswordService/Password/ModifyPasswordTests.cs
  PasswordVault.ServicesTests/PasswordService/User/LoginTests.cs
  PasswordVault.ServicesTests/PasswordServiceTests.cs
Labels: feature, frontend

#82 IS31 Password Requirement Tooltip
  PasswordVault.Desktop.Winforms/Presenters/LoginPresenter.cs
  PasswordVault.Desktop.Winforms/Views/AboutView.cs
  PasswordVault.Desktop.Winforms/Views/ChangePasswordView.cs
  PasswordVault.Desktop.Winforms/Views/Controls/AdvancedMenuStrip.cs
  PasswordVault.Desktop.Winforms/Views/ILoginView.cs
  PasswordVault.Desktop.Winforms/Views/LoginView.Designer.cs
  PasswordVault.Desktop.Winforms/Views/LoginView.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
  PasswordVault.Desktop.Winforms/Views/UIHelper.cs
Labels: feature, frontend

#83 IS62 Document Services
  PasswordVault.Services/AuthenticationService/IAuthenticationService.cs
  PasswordVault.Services/EncryptionService/AesEncryption.cs
  PasswordVault.Services/EncryptionService/IEncryptionService.cs
  PasswordVault.Services/EncryptionService/RijndaelManagedEncryption.cs
  PasswordVault.Services/KeyGenerator.cs
  PasswordVault.Services/MasterPasswordService/IMasterPassword.cs
  PasswordVault.Services/PasswordService/IPasswordService.cs
  PasswordVault.Services/TokenService/ITokenService.cs
  PasswordVault.Services/UserService/IUserService.cs
Labels: backend, documentation

#86 IS80 Delete User Warning
  PasswordVault.Data/SQLiteDatabase.cs
  PasswordVault.Desktop.Winforms/NinjectBindings.cs
  PasswordVault.Desktop.Winforms/PasswordVault.Desktop.Winforms.csproj
  PasswordVault.Desktop.Winforms/Presenters/ConfirmDeleteUserPresenter.cs
  PasswordVault.Desktop.Winforms/Presenters/MainPresenter.cs
  PasswordVault.Desktop.Winforms/Program.cs
  PasswordVault.Desktop.Winforms/Views/ConfirmDeleteUserView.Designer.cs
  PasswordVault.Desktop.Winforms/Views/ConfirmDeleteUserView.cs
  PasswordVault.Desktop.Winforms/Views/ConfirmDeleteUserView.resx
  PasswordVault.Desktop.Winforms/Views/IConfirmDeleteUserView.cs
  PasswordVault.Desktop.Winforms/Views/IMainView.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
Labels: feature, frontend

#92 Fix Package Issues
  PasswordVault.Desktop.Winforms/PasswordVault.Desktop.Winforms.csproj
  PasswordVault.Desktop.Winforms/packages.config
  PasswordVault.ServicesTests/PasswordVault.ServicesTests.csproj
Labels: bug

#94 Add clear button and increase show password font
  PasswordVault.Desktop.Winforms/Views/MainView.Designer.cs
  PasswordVault.Desktop.Winforms/Views/MainView.cs
  PasswordVault.Desktop.Winforms/Views/ShowPasswordView.Designer.cs
  PasswordVault.Desktop.Winforms/Views/ShowPasswordView.cs
Labels: feature, frontend
